### PR TITLE
[HAL-1578] Tests for custom title settings

### PR DESCRIPTION
**Pull request by honza-kasik**

### CODE REVIEW

**Comment by honza-kasik** [comment]
@zebrik @spriadka Can one of you guys please take a look and tell me if I done anything wrong? :)

**Comment by honza-kasik** [comment]
Tests will be edited for new implementation...

**Comment by honza-kasik** [comment]
Ready to be merged...

**Comment by spriadka** [comment]
Thanks @honza-kasik for the contribution :+1: . Merging!

**Pull request merged**
